mojohaus/animal-sniffer

- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
The return type may not exist in the known classes map.
Fixes #8
> Avoid NPE in SignatureChecker$CheckingVisitor.find

- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureBuilder.java
Animal Sniffer 1.14 introduced a regression. The including and excluding of classes in the configuration does not work correctly (it works correctly with 1.13).
The error is introduced in class `SignatureBuilder` while processing the inclusions and exclusions. Only the last inclusion and exclusion are taken into account.
As an example:
When scanning the JDK 1.8 with the inclusion
```
<includeClasses>
<includeClass>java.*</includeClass>
<includeClass>javax.*</includeClass>
<includeClass>org.ietf.jgss.*</includeClass>
<includeClass>org.omg.*</includeClass>
<includeClass>org.w3c.dom.*</includeClass>
<includeClass>org.xml.sax.*</includeClass>
</includeClasses>
```
leads to a class count of 45 classes.
With the proposed change the plugin recognizes 8040 classes.
> Changed Animal Sniffer to recognize included and excluded classes correctly.

- animal-sniffer-enforcer-rule/src/main/java/org/codehaus/mojo/animal_sniffer/enforcer/CheckSignatureRule.java
- animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
This change allows the user to specify the fully-qualified Maven artifact path for an API signature packages on the command line.  This allows for configuration-less invocation of the plugin like this:
```bash
mvn org.codehaus.mojo:animal-sniffer-maven-plugin:1.15-SNAPSHOT:check -Danimal.sniffer.signature=org.codehaus.mojo.signature:java16:1.0
```
This is especially useful when wrangling in API restriction checks even if they aren't configured in the POM.  This can be used as a post-job step in Jenkins, for example.
> Allow invocation without POM config.

- animal-sniffer/pom.xml
animal-sniffer is currently using ASM 5.0.2; it should be updated to 5.2. Here's the changelog: http://asm.ow2.org/history.html
> Update to ASM 5.2

- .travis.yml
Just noticed that the Travis build was not verifying compatibility with the current Maven release.
@reviewbybees for my colleagues
> Test also against Maven 3.5.0

- animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java
Allows a new configuration property 'failOnError' which is true by default to maintain current behavior. The new property lets users not fail the build if errors are found, but simply to allow the error messages to be shown.
Sorry, I do not know how to work with Ant tasks to also update that one.
> [FIXED #33] allow config to not fail the build on violations

- .travis.yml
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/ClassFileVisitor.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/Clazz.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureBuilder.java
- pom.xml
This PR allows to capture signatures of JMOD files with latest version of ASM. Tested with Oracle JDK 10.0.2.
ASM Changelog: https://asm.ow2.io/versions.html
5 August 2018: ASM 6.2.1 (tag ASM_6_2_1)
small improvements
!177: Ensure instructions belong only to one list
!178: Allow setting stack values in analysis frames
!179: Multiple methods for initializing analysis values
!181: Improve exception messages when exceeding classfile limits
!182: Minor Javadoc improvements
bug fixes
317609: Enhance ClassWriter to take a class loader for use with getCommonSuperClass
317833: When ClassWriter copies constant pool of class reader, ClassWriter.COMPUTE_MAX does not consider changes in argument sizes
317835: COMPUTE_MAX_STACK_AND_LOCAL_FROM_FRAMES does not handle LONG and DOUBLE types correctly …
> Capture signatures from JDK9/10 JMOD files

- .travis.yml
Travis has removed OpenJDK10 as it reached end of life Oct 2018
> Switch from openjdk10 to oraclejdk11

- animal-sniffer-enforcer-rule/src/main/java/org/codehaus/mojo/animal_sniffer/enforcer/CheckSignatureRule.java
- animal-sniffer-enforcer-rule/src/site/apt/examples/checking-signatures.apt.vm
- animal-sniffer-enforcer-rule/src/site/apt/usage.apt.vm
- animal-sniffer-maven-plugin/src/it/github-5-test-classes/invoker.properties
- animal-sniffer-maven-plugin/src/it/github-5-test-classes/pom.xml
- animal-sniffer-maven-plugin/src/it/github-5-test-classes/src/test/java/localhost/Main.java
- animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java
- pom.xml
Fixes #5.
Note: The first commit is fixing the following bogus error when running ` mvn clean verify -f animal-sniffer-maven-plugin/ -Prun-its`:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (mojo-enforcer-rules) @ animal-sniffer-maven-plugin ---
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequirePluginVersions failed with message:
Some plugins are missing valid versions:(LATEST RELEASE SNAPSHOT are not allowed )
org.apache.maven.plugins:maven-compiler-plugin.         The version currently in use is 3.8.0
org.apache.maven.plugins:maven-surefire-plugin.         The version currently in use is 2.22.0
org.apache.maven.plugins:maven-jar-plugin.      The version currently in use is 3.0.2
org.apache.maven.plugins:maven-clean-plugin.    The version currently in use is 3.0.0 …
```
> Fix #5: check test classes

- animal-sniffer-enforcer-rule/src/main/java/org/codehaus/mojo/animal_sniffer/enforcer/CheckSignatureRule.java
- animal-sniffer-maven-plugin/src/it/github-5-test-classes/pom.xml
- animal-sniffer-maven-plugin/src/it/github-5-test-classes/src/test/java/localhost/Main.java
- animal-sniffer-maven-plugin/src/it/github-5-test-classes/verify.groovy
- animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java
Resolves #5 (the false negatives after the initial PR for that issue).
> Fix #5: fix false negatives when checking test classes

- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/ClassFileVisitor.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureBuilder.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
- SignatureChecker: upgraded from ASM5 to ASM7
- ClassFileVisitor: added ability to process Paths (nedded for "jrt:/modules")
- SignatureBuilder: added java version switch (<=8 / >=9) and implemented signature creation for java 9+
> Enabled java9+ compatibility

- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/ClassListBuilder.java
Fixes #134
I saw the above error when building a work project that uses animal-sniffer. That work project uses JDK 11 but compiles some modules for JDK 8 and uses animal-sniffer to verify correct JDK 8 api usage. I grepped the animal-sniffer code and found one remaining occurrence of ASM5. After Replacing it with ASM7, and doing a local `mvn clean install` on animal-sniffer, my work project built correctly.
Related to this PR: https://github.com/mojohaus/animal-sniffer/pull/91
> Fix "NestMember requires ASM7"

- animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
Loading JDK signatures can take more than half a second, so when the build contains lots of modules, it can save a lot of time
> Cache signatures so that multiple runs of the mojo can reuse loaded signatures

- animal-sniffer-maven-plugin/src/it/manimalsniffer-49/invoker.properties
- animal-sniffer-maven-plugin/src/it/manimalsniffer-49/verify.groovy
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
This removes incorrect covariant return type handling introduced in MANIMALSNIFFER-49. The ticket is no longer publicly accessible, so I lack the context of the original change.
The block of code removed in this PR prevented animalsniffer from catching covariant changes to return types which were compile-time compatible but not binary-compatible.
For example, if we take the code below
```
ByteBuffer buffer = ...
buffer.rewind();
```
and compile it on Java 8, we'll get bytecode which invokes
```
java.nio.ByteBuffer.rewind()Ljava/nio/Bufffer
```
If we compile it on Java 9+, while still targeting Java 8, we will get bytecode which invokes
```
java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer
```
That's because this method with the more specific `ByteBuffer` return type is available in JDK9+. …
> Remove incorrect handling of covariant return types

- .github/workflows/maven.yml
Signed-off-by: Olivier Lamy <olamy@apache.org>
> use Apache Maven shared gha v3 and add matrix setup

- README.md
- src/site/apt/index.apt
Replaces the Travis badge with a GitHub Actions badge.
> Use HTTPS links in README and replace Travis badge

- animal-sniffer-annotations/src/main/java/org/codehaus/mojo/animal_sniffer/IgnoreJRERequirement.java
- animal-sniffer-maven-plugin/pom.xml
- animal-sniffer-maven-plugin/src/it/fields/invoker.properties
- animal-sniffer-maven-plugin/src/it/fields/pom.xml
- animal-sniffer-maven-plugin/src/it/fields/src/main/java/localhost/Test.java
- animal-sniffer-maven-plugin/src/it/fields/src/main/java/localhost/TestSuppressedClass.java
- animal-sniffer-maven-plugin/src/it/fields/src/main/java/localhost/TestSuppressedField.java
- animal-sniffer-maven-plugin/src/it/fields/src/main/java/localhost/TestWithNested.java
- animal-sniffer-maven-plugin/src/it/fields/src/main/java/localhost/TestWithNestedSuppressedClass.java
- animal-sniffer-maven-plugin/src/it/fields/verify.groovy
- animal-sniffer-maven-plugin/src/it/github-74-1/verify.groovy
- animal-sniffer/pom.xml
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
- animal-sniffer/src/test/java/org/codehaus/mojo/animal_sniffer/SignatureCheckerTest.java
- Fixes #131
- Resolves #132
- Adds `ElementType.FIELD` as possible target to `IgnoreJRERequirement`
Feedback is appreciated! If you want I can also split the commits into separate pull requests.
> Improve field handling

- animal-sniffer-enforcer-rule/pom.xml
- animal-sniffer-maven-plugin/pom.xml
- pom.xml
Get rid of Maven2 bits, put Maven3 bits in proper scope.
> Update plugin, require Maven 3.2.5

- README.md
- animal-sniffer-annotations/src/site/site.xml
- animal-sniffer-ant-tasks/pom.xml
- animal-sniffer-ant-tasks/src/site/apt/index.apt
- animal-sniffer-ant-tasks/src/site/site.xml
- animal-sniffer-enforcer-rule/src/site/apt/index.apt.vm
- animal-sniffer-enforcer-rule/src/site/site.xml
- animal-sniffer-maven-plugin/pom.xml
- animal-sniffer-maven-plugin/src/site/apt/index.apt
- animal-sniffer-maven-plugin/src/site/site.xml
- animal-sniffer/src/site/apt/index.apt.vm
- animal-sniffer/src/site/site.xml
- java-boot-classpath-detector/src/site/site.xml
- pom.xml
- src/site/site.xml
- improve site build
- fix broken links
- fix GitHub ribbon
fix #89 #100
> Refresh documentation site

- SECURITY.md
Closes #259
I've created the SECURITY.md file following a GitHub's template and considering that you'd request that users report vulnerabilities through the [security advisory](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability), which is a handy new GitHub feature, but it's still in beta and **has to be manually enabled by a maintainer**.
If you're interested in this feature, you can activate it following this steps:
1. Click on this [link](https://github.com/mojohaus/animal-sniffer/settings/security_analysis) to go to Code security & analysis section on your repo's settings
2. Click "Enable" for "Private vulnerability reporting (Beta)"
However, if you'd rather not use this feature, you can also …
> Docs: create Security Policy

- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/ClassFileVisitor.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/Clazz.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureBuilder.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureMerger.java
- animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureObjectInputStream.java
- animal-sniffer/src/test/java/org/codehaus/mojo/animal_sniffer/SignatureCheckerTest.java
Because signature files are created using Java Serialization, adds a new `SignatureObjectInputStream` which restricts the classes which are allowed to be loaded when reading signature files to increase security.
I hope these changes are fine security-wise, but please let me know if I overlooked something or failed to consider something.
I have tested these changes with the following signatures to make sure that they can still be loaded successfully:
- [`org.codehaus.mojo.signature:java12:1.0`](https://search.maven.org/artifact/org.codehaus.mojo.signature/java12/1.0/pom)
- [`org.codehaus.mojo.signature:java18:1.0`](https://search.maven.org/artifact/org.codehaus.mojo.signature/java18/1.0/pom)
- [`net.sf.androidscents.signature:android-api-level-1:1.0_r2`](https://search.maven.org/artifact/ne …
> Restrict allowed classes during deserialization of signature files
